### PR TITLE
Remove DataStructures dependency

### PR DESCRIPTION
**Pull request by EricForgy**
Have a look. No tests, but a pretty simple fix. Hope it is alright 🙏

### CODE REVIEW

**Comment by nkottary** [comment]
LGTM!

**Comment by EricForgy** [comment]
Let me know if there is anything else I might be able to help. A lot of people (including me) will be very happy once this package is ready. Happy to help 😊

**Comment by nkottary** [comment]
This can be merged @StefanKarpinski

**Comment by nkottary** [comment]
I may need help testing. Will let you know.

**Pull request merged**
